<a href="https://colab.research.google.com/github/MdBilal420/pytorch-fundamentals/blob/main/pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
a = torch.tensor([[1,2,3],[6,8,9]])
b = torch.tensor([4,5,6])
print(a+b)

tensor([[ 5,  7,  9],
        [10, 13, 15]])


In [ ]:
print(a*b)

tensor([[ 4, 10, 18],
        [24, 40, 54]])


In [ ]:
matmul1 = torch.matmul(a,b)
matmul2 = torch.matmul(b,a.T)
print(matmul1)
print(matmul2)

tensor([ 32, 118])
tensor([ 32, 118])


In [ ]:
a.min()

tensor(1)

In [ ]:
a.max()

tensor(9)

In [ ]:
a.type(torch.float32).mean()

tensor(4.8333)

In [ ]:
b.argmax()

tensor(2)

In [ ]:
a.argmin()

tensor(0)

In [ ]:
b[0], b[2]

(tensor(4), tensor(6))

In [ ]:
a = torch.arange(1,10)
a

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
z = a[:5]
z

tensor([1, 2, 3, 4, 5])

In [ ]:
z=a

In [ ]:
z[:5] = 9
z,a

(tensor([9, 9, 9, 9, 9, 6, 7, 8, 9]), tensor([9, 9, 9, 9, 9, 6, 7, 8, 9]))

In [ ]:
x = torch.rand( 2,1,2,3)
x,x.dim(),x.shape

(tensor([[[[0.6732, 0.3548, 0.0442],
           [0.2838, 0.9354, 0.2045]]],
 
 
         [[[0.7116, 0.9019, 0.7633],
           [0.1762, 0.2986, 0.8847]]]]),
 4,
 torch.Size([2, 1, 2, 3]))

In [ ]:
x_squeeze = x.squeeze()
x_squeeze, x_squeeze.shape

(tensor([[[0.0196, 0.5683, 0.3819],
          [0.3853, 0.0862, 0.2745]],
 
         [[0.9208, 0.4290, 0.5979],
          [0.7779, 0.2534, 0.9201]]]),
 torch.Size([2, 2, 3]))

In [ ]:
x_squeeze1 = x_squeeze.unsqueeze(dim=2)
x_squeeze1, x_squeeze1.shape

(tensor([[[[0.0196, 0.5683, 0.3819]],
 
          [[0.3853, 0.0862, 0.2745]]],
 
 
         [[[0.9208, 0.4290, 0.5979]],
 
          [[0.7779, 0.2534, 0.9201]]]]),
 torch.Size([2, 2, 1, 3]))

In [ ]:
x = torch.randn(2, 3, 5)
x, x.shape

(tensor([[[ 0.6419,  0.7344,  0.3451, -0.2061, -0.1311],
          [-0.1666,  1.7670, -0.5733, -0.0704, -0.1852],
          [ 0.8937,  0.8323,  2.2911,  0.4659, -1.3546]],
 
         [[ 0.9821, -0.2659, -1.4232, -1.1113,  0.3396],
          [ 0.4574, -1.2466, -0.9371, -1.5612,  0.6872],
          [-2.1168,  2.0703, -1.1010, -0.7693, -0.5936]]]),
 torch.Size([2, 3, 5]))

In [ ]:
x_permuted = x.permute(2, 0, 1)
x_permuted, x_permuted.shape

(tensor([[[ 0.6419, -0.1666,  0.8937],
          [ 0.9821,  0.4574, -2.1168]],
 
         [[ 0.7344,  1.7670,  0.8323],
          [-0.2659, -1.2466,  2.0703]],
 
         [[ 0.3451, -0.5733,  2.2911],
          [-1.4232, -0.9371, -1.1010]],
 
         [[-0.2061, -0.0704,  0.4659],
          [-1.1113, -1.5612, -0.7693]],
 
         [[-0.1311, -0.1852, -1.3546],
          [ 0.3396,  0.6872, -0.5936]]]),
 torch.Size([5, 2, 3]))

In [ ]:
x_permuted[2,0,1]

tensor(-0.5733)

In [ ]:
import numpy as np

In [ ]:
array = np.arange(1,8)
tensor = torch.from_numpy(array).type(torch.float32)
array, tensor


(array([1, 2, 3, 4, 5, 6, 7]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [ ]:
array.dtype, tensor.dtype

(dtype('int64'), torch.float32)

In [ ]:
tensor = torch.arange(1,10,2)
tensor


tensor([1, 3, 5, 7, 9])

In [ ]:
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1, 3, 5, 7, 9]), array([1, 3, 5, 7, 9]))

In [ ]:
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_A = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


Access GPU/CPU

In [ ]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
tensor = torch.tensor([1,2,3])
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [ ]:
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [ ]:
!nvidia-smi

Wed Aug 14 01:33:23 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   69C    P0              31W /  70W |    105MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--