<a href="https://colab.research.google.com/github/MdBilal420/pytorch-fundamentals/blob/main/pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
a = torch.tensor([[1,2,3],[6,8,9]])
b = torch.tensor([4,5,6])
print(a+b)

tensor([[ 5,  7,  9],
        [10, 13, 15]])


In [ ]:
print(a*b)

tensor([[ 4, 10, 18],
        [24, 40, 54]])


In [8]:
matmul1 = torch.matmul(a,b)
print(matmul1)

tensor([ 32, 118])
