<a href="https://colab.research.google.com/github/MdBilal420/pytorch-fundamentals/blob/main/pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch

In [ ]:
a = torch.tensor([[1,2,3],[6,8,9]])
b = torch.tensor([4,5,6])
print(a+b)

tensor([[ 5,  7,  9],
        [10, 13, 15]])


In [ ]:
print(a*b)

tensor([[ 4, 10, 18],
        [24, 40, 54]])


In [ ]:
matmul1 = torch.matmul(a,b)
matmul2 = torch.matmul(b,a.T)
print(matmul1)
print(matmul2)

tensor([ 32, 118])
tensor([ 32, 118])


In [ ]:
a.min()

tensor(1)

In [ ]:
a.max()

tensor(9)

In [ ]:
a.type(torch.float32).mean()

tensor(4.8333)

In [ ]:
b.argmax()

tensor(2)

In [ ]:
a.argmin()

tensor(0)

In [ ]:
b[0], b[2]

(tensor(4), tensor(6))

In [4]:
a = torch.arange(1,10)
a

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
z = a[:5]
z

tensor([1, 2, 3, 4, 5])

In [6]:
z=a

In [7]:
z[:5] = 9
z,a

(tensor([9, 9, 9, 9, 9, 6, 7, 8, 9]), tensor([9, 9, 9, 9, 9, 6, 7, 8, 9]))

In [44]:
x = torch.rand( 2,1,2,3)
x,x.dim(),x.shape

(tensor([[[[0.6732, 0.3548, 0.0442],
           [0.2838, 0.9354, 0.2045]]],
 
 
         [[[0.7116, 0.9019, 0.7633],
           [0.1762, 0.2986, 0.8847]]]]),
 4,
 torch.Size([2, 1, 2, 3]))

In [43]:
x_squeeze = x.squeeze()
x_squeeze, x_squeeze.shape

(tensor([[[0.0196, 0.5683, 0.3819],
          [0.3853, 0.0862, 0.2745]],
 
         [[0.9208, 0.4290, 0.5979],
          [0.7779, 0.2534, 0.9201]]]),
 torch.Size([2, 2, 3]))

In [54]:
x_squeeze1 = x_squeeze.unsqueeze(dim=2)
x_squeeze1, x_squeeze1.shape

(tensor([[[[0.0196, 0.5683, 0.3819]],
 
          [[0.3853, 0.0862, 0.2745]]],
 
 
         [[[0.9208, 0.4290, 0.5979]],
 
          [[0.7779, 0.2534, 0.9201]]]]),
 torch.Size([2, 2, 1, 3]))

In [57]:
x = torch.randn(2, 3, 5)
x, x.shape

(tensor([[[ 0.6419,  0.7344,  0.3451, -0.2061, -0.1311],
          [-0.1666,  1.7670, -0.5733, -0.0704, -0.1852],
          [ 0.8937,  0.8323,  2.2911,  0.4659, -1.3546]],
 
         [[ 0.9821, -0.2659, -1.4232, -1.1113,  0.3396],
          [ 0.4574, -1.2466, -0.9371, -1.5612,  0.6872],
          [-2.1168,  2.0703, -1.1010, -0.7693, -0.5936]]]),
 torch.Size([2, 3, 5]))

In [58]:
x_permuted = x.permute(2, 0, 1)
x_permuted, x_permuted.shape

(tensor([[[ 0.6419, -0.1666,  0.8937],
          [ 0.9821,  0.4574, -2.1168]],
 
         [[ 0.7344,  1.7670,  0.8323],
          [-0.2659, -1.2466,  2.0703]],
 
         [[ 0.3451, -0.5733,  2.2911],
          [-1.4232, -0.9371, -1.1010]],
 
         [[-0.2061, -0.0704,  0.4659],
          [-1.1113, -1.5612, -0.7693]],
 
         [[-0.1311, -0.1852, -1.3546],
          [ 0.3396,  0.6872, -0.5936]]]),
 torch.Size([5, 2, 3]))