<a href="https://colab.research.google.com/github/MdBilal420/pytorch-fundamentals/blob/main/pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
a = torch.tensor([[1,2,3],[6,8,9]])
b = torch.tensor([4,5,6])
print(a+b)

tensor([[ 5,  7,  9],
        [10, 13, 15]])


In [ ]:
print(a*b)

tensor([[ 4, 10, 18],
        [24, 40, 54]])


In [10]:
matmul1 = torch.matmul(a,b)
matmul2 = torch.matmul(b,a.T)
print(matmul1)
print(matmul2)

tensor([ 32, 118])
tensor([ 32, 118])


In [11]:
a.min()

tensor(1)

In [12]:
a.max()

tensor(9)

In [14]:
a.type(torch.float32).mean()

tensor(4.8333)

In [18]:
b.argmax()

tensor(2)

In [19]:
a.argmin()

tensor(0)

In [20]:
b[0], b[2]

(tensor(4), tensor(6))